### PR TITLE
UIIN-1368: Update permission for because of renaming of instance-bulk endpoint

### PR DESCRIPTION
**Pull request by ViktorSoroka07**
## Purpose

Update permission for because of the renaming of instance-bulk endpoint in the scope of the [UIIN-1368](https://issues.folio.org/browse/UIIN-1368).

### CODE REVIEW

**Comment by ViktorSoroka07** [comment]
@zburke, @mkuklis please review.

**Review by mkuklis — APPROVED** [review]

**Review by zburke — CHANGES_REQUESTED** [review]
Please update the module version to `2.0.0` in `package.json` as you have in CHANGELOG.md.

**Comment by ViktorSoroka07** [comment]
@zburke, done.

**Review by zburke — APPROVED** [review]

**Comment by ViktorSoroka07** [comment]
@zak, please merge as I don't have rights.

**Pull request merged**
